[package]
name = "test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3"
rppal = { version = "0.12.0", features = ["hal"] }

lsm9ds1 = { path = "../.."}

